*** Variables ***
${mail}             sysadmin@qacoders.com
${password}         1234@Test 
 # usuário

${fullName}                 Fulano da Silva Santos
${accessProfile}            ADMIN
${fullName23}               Fulano da Silva Santos34
${fullName##}               Fulano da Silva Santos#@
${fullNameminusculo}        fulano da silva santos
${fullName101carc}          Jussara Maria Mariana Muriá da Silva Penha dos Santos Sousa Oliveira Alves Carvalho Maia Marianoconsi
${fullName100carc}          Kussara Maria Mariana Muriá da Silva Penha dos Santos Sousa Oliveira Alves Carvalho Maia Marianocond
${emailespacodominio}       fulanodasila @qa .coders.com
${emailinválido}            fulana.coders.com
${password13}               123456@Testest
${password7}                123#asD
${password8}                12aA567@
${confirmarsenhadif}        123456@Tett
${perfildeacessoinva}       ADMINISTRADOR
${CPF10}                    1234567890
${CPF12}                    123456789012

#  departamento
${Departmentname}           AlanDeparrtubarao
${DepartamentMaiuscula}     FLONANCEGASTEITUDNAOTEMANA
${departamentominusculo}    finajgtjojotooololo
${departamentnumero}        Deamentargeto2 Financas2
${department&}              Ablue&wbaleimmaaaa&blue
${department@@@#}           Advogacia#@
${departamento51}           departamentooooooooooooooooooooooooooosssssssssssso
${departament50}            Kelartaponteoooooooooooooooooooooooooosssssssssssa
# diretoria
${boardname}                Direpatata  
${boardMaiusculo}           DIVEOBANCO
${boardminuscula}           rumabaleiavivasnomar
${board&}                   Rosada&florrosa
${boardnumero}              Secretariaia12
${boardcaractere#}          Secretariaia@#
